custom_config_entity.default_entity.*:
  type: config_entity
  label: 'Default entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    title:
      type: string
      label: 'Title'
    description:
      type: string
      label: 'Description'
    uuid:
      type: string
