
# Custom config entity menu items definition
entity.my_custom_entities:
  title: 'My custom entities'
  route_name: custom_config_entity.custom_entities
  description: 'Here a links for my custom entities'
  parent: system.admin_structure

entity.custom_config_entity.collection:
  title: 'Custom config entity'
  route_name: entity.custom_config_entity.collection
  description: 'List Custom config entity (bundles)'
  parent: entity.my_custom_entities
  weight: 99
